### ISSUE TITLE
Remove unnecessary outputs from packages

### ISSUE THREAD

**Issue by deemp** [thomashoneyman/purescript-overlay#37]
Hi! Thank you for your work.

I noticed that packages like `purs-unstable` and `spago-unstable` have `package.json` as an output while `spago` and `purs` don't. Also the latter packages provide completions while the former don't.

Is this an expected behavior?

I wanted to use the unstable packages in a `devShell`, but there was a collision between `package.json`-s. 
I excluded `package.json` from outputs by adding a phase.

```nix
inherit (pkgs.extend inputs.purescript-overlay.overlays.default) purs spago-unstable purs-tidy purix;

spago = spago-unstable.overrideAttrs (x: {
  phases = [ "buildPhase" "installPhase" "postInstallPhase" ];
  postInstallPhase = ''
    rm -rf $out/package.json
  '';
});
```

**Comment by thomashoneyman** [comment]
The package.json is probably a holdover from when spago was built from source using slimlock; I think it can safely be removed from both (and that completions can be provided).

The unstable and stable versions should be identical. The only difference should be naming.

**Comment by deemp** [comment]
I tried a `devShell` in this repository, and there was no collision between `package.json`s for unstable versions. Also, builds fail when `package.json` isn't moved in `mkSpagoDerivation`.

I suppose it's a problem on my side as I used `numtide/devshell`.

So, I'll open an issue just for completions.
