### ISSUE TITLE
Suggestion to include `purescript-language-server` in example

### ISSUE THREAD

**Issue by peterbecich** [thomashoneyman/purescript-overlay#44]
Can `purescript-language-server` be included in the default usage example in the readme?

https://github.com/nwolverson/purescript-language-server

Here it is in NixPkgs:
https://search.nixos.org/packages?channel=unstable&show=nodePackages_latest.purescript-language-server&from=0&size=50&sort=relevance&type=packages&query=purescript-language-server

This would be similar to how `haskell-language-server` is provided by default in the `haskell-flake` `develop` shell: https://github.com/srid/haskell-flake

Thank you

**Comment by thomashoneyman** [comment]
Added in #46
