### ISSUE TITLE
Automatically upgrade spago@next

### ISSUE THREAD

**Issue by f-f** [thomashoneyman/purescript-overlay#47]
Latest release is 0.93.13, but the latest one here is 0.93.9 - from the commit log it seems there's some machinery for automatically upgrading packages, but it looks like that's not in place for Spago.

**Comment by f-f** [comment]
```bash
$ nix run .\#generate prefetch ../manifests
...
Listing releases for repo purescript/spago
Octokit: requesting GET /repos/purescript/spago/releases
Retrieved 52 releases for spago
Found 0 new releases for spago
No new spago releases.
```

Ah I see, it's looking for github releases, but all the spago@next releases are only on npm

**Comment by thomashoneyman** [comment]
Mm — maybe we can adjust to list NPM releases, then. I don’t mind doing that instead.

**Comment by f-f** [comment]
We will start doing releases on GitHub once again (the release CI needs redoing), but the tarball to fetch should be the NPM one anyways. I guess #48 is a good patch in the meantime

**Comment by thomashoneyman** [comment]
Oh — in that case it will be fine because we fetch releases from GitHub but tarballs from npm. I don’t think we auto-update for spago right now because I didn’t want to automatically pull in the pre-releases but we can go ahead and support that now.

**Comment by f-f** [comment]
Spago 0.93.15 is now shipping with sqlite, and the overlay build doesn't seem to like that:

```
++ '[' ']'
++ '[' ']'
+++ /nix/store/c8apliw1gcqv08h4b9qhy0xjdpmcrm4v-spago-0.93.15/bin/spago --version
++ VERSION='node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '\''better-sqlite3'\'' imported from /nix/store/c8apli>
    at new NodeError (node:internal/errors:399:5)
    at packageResolve (node:internal/modules/esm/resolve:889:9)
    at moduleResolve (node:internal/modules/esm/resolve:938:20)
    at defaultResolve (node:internal/modules/esm/resolve:1153:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: '\''ERR_MODULE_NOT_FOUND'\''
}

Node.js v18.16.1'
+ exitHandler
+ exitCode=1
+ set +e
+ '[' -n '' ']'
+ ((  1 != 0  ))
+ runHook failureHook
+ local hookName=failureHook
+ shift
+ local 'hooksSlice=failureHooks[@]'
+ local hook
+ for hook in "_callImplicitHook 0 $hookName" ${!hooksSlice+"${!hooksSlice}"}
+ _eval '_callImplicitHook 0 failureHook'
+ declare -F '_callImplicitHook 0 failureHook'
+ eval '_callImplicitHook 0 failureHook'
++ _callImplicitHook 0 failureHook
++ local def=0
++ local hookName=failureHook
++ declare -F failureHook
++ type -p failureHook
++ '[' -n '' ']'
++ return 0
+ return 0
+ '[' -n '' ']'
+ return 1
```

**Comment by thomashoneyman** [comment]
Looks like we'll need to make sure that's available in a node_modules directory along with the executable JS file. In the registry we do this via slimlock:

https://github.com/thomashoneyman/slimlock#usage

**Comment by thomashoneyman** [comment]
@f-f the reason `better-sqlite3` isn't available (while all other dependencies are) is because it's marked external in the package:

https://github.com/purescript/spago/blob/d398cba6b4b7a56640f7ec6e2b079e659068a3af/bin/spago.yaml#L30C1-L31

Is this intentional? If so, I can still include it manually, but the NPM registry doesn't expose a package-lock.json so I am going to have to guess at the version of better-sqlite3 to include in the Nix builds.

**Comment by thomashoneyman** [comment]
It was added in this commit:
https://github.com/purescript/spago/commit/2f348a3e0aebd9d99ab559055e9ac624f76990fc

**Comment by f-f** [comment]
It's marked as external because the bundle would not work otherwise - I haven't investigated this further since I found this workaround, but I'm very open to a better solution if there's one.

The package is included in the package.json dependencies even if it's external to the bundle, is that not enough?

**Comment by thomashoneyman** [comment]
> The package is included in the package.json dependencies even if it's external to the bundle, is that not enough?

It's just that I would prefer to use the exact version that Spago is using at the time the bundle is created, and the package.json provides a range. I could probably fetch the package-lock.json from the related Git tag, though.

**Comment by f-f** [comment]
I think it would be very fine to just get the latest version from that dependency range - if that doesn't work then the range is broken and we ought to fix it
