### ISSUE TITLE
Set meta.mainProgram, use lib.getExe

### ISSUE THREAD

**Issue by toastal** [thomashoneyman/purescript-overlay#68]
Apps are using something like `bin/${bin.pname or bin.name}`. This is a bit hacky/brittle, but happens to work in all current cases. There’s already a `meta` place to set the main program--which can be used in tandem with `lib.getExe` (which calls `mainProgram` from `$src/bin`). There wouldn’t be a huge code reduction or anything, but would follow more expectations & could help downstream users, especially if not familiar with the tooling. If projects upstream in `nixpkgs` need their `meta.mainProgram` set, I can look into that.

**Comment by thomashoneyman** [comment]
That’s totally fine with me! To be honest I don’t really know the typical Nix patterns and wrote this just to make sure I have access to these tools at various versions. If you notice improvements like what you just suggested I’m more than happy to integrate them

**Comment by toastal** [comment]
Of note: https://github.com/NixOS/nixpkgs/pull/282080

**Comment by toastal** [comment]
I would have to look at how slimlock or whatever it is implemented to see if it adds the `mainProgram`, but I opened a merge request to Nixpkgs to add them without this overlay as a start. If you wanted to review it, it could help the Nix maintainers to get a LGTM (if it looks good to you).

**Comment by thomashoneyman** [comment]
`slimlock` isn't used in this repo except for the `generate` script itself (none of the apps use it).

**Comment by deemp** [comment]
Sorry, didn't see this issue before makin a PR. I added `mainProgram` there. Should I extract that change into a new PR?

**Comment by toastal** [comment]
I don’t think it matters. On other review models, the PR doesn’t matter… the individual patches do so if you have a separate patch about switching to lib.getExe, I wouldn’t see the problem.

**Comment by toastal** [comment]
These should now be merging after https://github.com/NixOS/nixpkgs/pull/282080; see status
https://nixpk.gs/pr-tracker.html?pr=282080
