### ISSUE TITLE
Remove flake-utils from the README / docs

### ISSUE THREAD

**Issue by toastal** [thomashoneyman/purescript-overlay#69]
Great to see the ‘real’ flake doesn’t include unnecessary downstream dependencies, and while that is setting a good example(!), maybe the README docs should be updated as well so that folks that want a copy-paste solution don’t incur additional dependencies to audit or unknowingly cause downstream users of their projects to also have more dependencies than needed infecting their lockfiles. My question would actually be if `genAttrs` or similar would be considered more helpful, or noisy/confusing to those users.

**Comment by thomashoneyman** [comment]
I'd accept a PR that removes flake-utils in favor of genAttrs. I don't really mind either way — just want a simple little copy/paste example people can use.

**Comment by toastal** [comment]
I can look into that tomorrow perhaps.
