### ISSUE TITLE
Example in the README appears to be broken

### ISSUE THREAD

**Issue by postsolar** [thomashoneyman/purescript-overlay#72]
README usage example doesn't work.
There's an extra `};` in the end, a typo in `outputs = { self, nixpkgs, ... }@input` (note the missing `s` in `@input`) and something is wrong with the usage of overlays (I'm too new to Nix to diagnose what it is exactly, or how to make it work).

After fixing the typos the error I'm getting is `attribute 'default' is missing` (line 19).

cc @toastal

**Comment by toastal** [comment]
Looking
-- 
toastal ไข่ดาว | https://toast.al
PGP: 7944 74b7 d236 dab9 c9ef  e7f9 5cce 6f14 66d4 7c9e

**Comment by postsolar** [comment]
I think I figured it out.

```nix
      nixpkgsFor = forAllSystems (system: import nixpkgs {
        inherit system;
        config = {};
        overlays = builtins.attrValues self.overlays; # instead of self.overlays.default
      });
```

and
```nix
        overlays = {
          default = inputs.purescript-overlay.overlays.default; # instead of naming it purescript
        }
```

This makes it work but I don't know if it matches the original intention. If it does then I could PR the changes.

**Comment by toastal** [comment]
Yeah that was a blunder focusing on the big ideas behind it, but not testing it since it was a README. I opened a merge request for it.

**Comment by postsolar** [comment]
Thank you! "Best practices" example with comments on what and why in the commit message of #70 is really helpful.
